services:
  pyde1:
    build:
      context: .
      args:
        - BROKER_HOSTNAME=broker
    ports:
      - 1234:1234
    depends_on:
      - broker
    networks:
      - mosquitto
    volumes:
      - ./db/:/var/lib/pyde1
    # for bluetooth pass-through
    privileged: true

  broker:
    image: eclipse-mosquitto:2.0.15
    ports:
      - 1883:1883
    networks:
      - mosquitto
    command: ["mosquitto", "-c", "/mosquitto-no-auth.conf"]

  test:
    build:
      dockerfile: test.Dockerfile
      context: ./

networks:
    mosquitto:
        name: mosquitto
        driver: bridge
